name: Render and Publish Quarto Website

on:
  push:
    branches:
      - main # O la rama desde la que quieres publicar

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Necesario para publicar en gh-pages

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.3.3' # Usa una versión reciente o 'latest'
          # use-public-rspm: true # Opcional: puede ayudar con la velocidad de descarga de paquetes

      - name: Install R Package System Dependencies (Optional but recommended)
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::rmarkdown
            any::knitr
            # Añade otros paquetes aquí si es necesario, especialmente los que se compilan desde fuente.
          cache-version: 1

      - name: Install R Dependencies
        run: |
          install.packages(c('rmarkdown', 'knitr', 'tidyverse')) # Añade todos tus paquetes
        shell: Rscript {0}

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        # with:
        #   version: "latest" # O una versión específica

      - name: Render Quarto Website
        uses: quarto-dev/quarto-actions/render@v2
        # with:
        #   path: . # Renderiza todo en el directorio raíz (ajusta si es necesario)

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3 # Una acción popular para desplegar a GitHub Pages
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _site # El directorio de salida por defecto de Quarto
          # user_name: 'github-actions[bot]' # Opcional
          # user_email: 'github-actions[bot]@users.noreply.github.com' # Opcional
          # cname: your.custom.domain.com # Si tienes un dominio personalizado